name: Update ads.txt

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # allows you to trigger manually too

jobs:
  update-ads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ads.txt
        run: |
          curl -L https://srv.adstxtmanager.com/19390/joshuajireh.info -o ads.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ads.txt
          git diff --cached --quiet || git commit -m "Update ads.txt from AdstxtManager"
          git push
